apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tote"
  description: A minimal kubernetes plugin
  annotations:
    backstage.io/kubernetes-id: tote
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: fotisolgr/tote
  tags:
    - quarkus
spec:
  type: service
  owner: user:fotisolgr
  lifecycle: experimental
  providesApis:
    - gcloud-api
  consumesApis:
    - users-api
