apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tote1
  annotations:
    github.com/project-slug: fotisolgr/tote
spec:
  type: service
  
  lifecycle: experimental
  owner: user:fotisolgr
