apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tote"
  description: A minimal kubernetes plugin
  annotations:
    backstage.io/kubernetes-id: tote
    github.com/project-slug: fotisolgr/tote
spec:
  type: service
  owner: user:fotisolgr
  lifecycle: experimental
