site_name: Tote documentation
repo_url: https://github.com/fotisolgr/tote/

nav:
  - Version 1.0.0:
    - Home: v1.0.0/home.md
    - About: v1.0.0/about.md
    - Contact: v1.0.0/contact.md
  - Version 1.0.1:
    - Home: v1.0.1/home.md
    - About: v1.0.1/about.md
    - Contact: v1.0.1/contact.md
plugins:
  - techdocs-core
  
theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist  
