site_name: Tote Documentation

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Versions:
    - v1.0.0: v1.0.0/
    - v1.0.1: v1.0.1/
  
theme: readthedocs

plugins:
  - techdocs-core:
      src: docs
      versions:
        - pattern: "v*.*.*"
          label: "vX.Y.Z"
