site_name: Tote documentation

nav:
  - Version 1.0.0:
    - Home: v1.0.0/index.md
    - About: v1.0.0/about.md
    - Contact: v1.0.0/contact.md
  - Version 1.0.1:
    - Home: v1.0.1/index.md
    - About: v1.0.1/about.md
    - Contact: v1.0.1/contact.md
plugins:
  - techdocs-core
  
theme:
  name: readthedocs
  features:
    - toc.integrate
